version: '3'

networks:
  proxy:
    external:
      name: direktkredit-proxy

volumes:
  certbot-config:
  certcot-www:

services:

  nginx:
    image: habidat/direktkredit-nginx
    container_name: direktkredit-nginx
    restart: unless-stopped
    volumes:
      - certbot-config:/habidat/certbot
      - certcot-www:/var/www/certbot
      - ./projects.json:/habidat/projects.json
    environment:
      - SSL_PROVIDER=certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    logging:
      options:
        max-size: 50m    

  smtp:
    image: namshi/smtp
    container_name: direktkredit-smtp
    restart: unless-stopped
    ports: 
      - 25
    networks:
      - proxy    
    logging:
      options:
        max-size: 50m    

  certbot:
    image: certbot/certbot
    container_name: direktkredit-certbot
    restart: unless-stopped
    volumes:
      - certbot-config:/etc/letsencrypt
      - certcot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"      
    logging:
      options:
        max-size: 50m    
